from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
from typing import Any


def sha256_file(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Qafila Evidence Coverage Candidate",
        "",
        "> Artifact-only candidate generated by the G-3 Evidence Coverage Agent. It does not update a tracked coverage file, open a pull request, or perform an external write.",
        "",
        "## Coverage status",
        "",
        "| Evidence item | Status | Measured result | Source artifact |",
        "|---|---|---|---|",
        f"| GH-01 deterministic run A | {summary['gh01']['run_a_status']} | {summary['gh01']['run_a_payload_hash']} | `{summary['gh01']['run_a_benchmark']}` |",
        f"| GH-01 deterministic run B | {summary['gh01']['run_b_status']} | {summary['gh01']['run_b_payload_hash']} | `{summary['gh01']['run_b_benchmark']}` |",
        f"| GH-01 comparison | {'covered' if summary['gh01']['matches'] else 'hold'} | matches={str(summary['gh01']['matches']).lower()} | `{summary['gh01']['comparison']}` |",
        f"| GH-02 negative suite | {'covered' if summary['gh02']['hold_count'] == summary['gh02']['fixture_count'] else 'hold'} | hold={summary['gh02']['hold_count']}/{summary['gh02']['fixture_count']} | `{summary['gh02']['hold_register']}` |",
        "",
        "## Policy and scope",
        "",
        f"- Policy version: `{summary['policy_version']}`",
        f"- Coverage contract: `{summary['schema_version']}`",
        f"- Event schema: `{summary['schema_version_event']}`",
        f"- Network egress: `{summary['network_egress']}`",
        "- External writes: `false`",
        "- Coverage classification: `candidate`; a human reviewer must decide whether any proposed claim is accepted.",
        "",
        "## Source integrity",
        "",
        "| Path | SHA-256 |",
        "|---|---|",
    ]
    for source in summary["sources"]:
        lines.append(f"| `{source['path']}` | `{source['sha256']}` |")
    lines.extend([
        "",
        "## Hold and review rule",
        "",
        "If any expected result is absent, mismatched, or incomplete, classify coverage as `hold` and do not export or mutate a tracked evidence register. This report is evidence about the current workflow run, not a legal, commercial, or autonomous approval.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Qafila G-3 evidence coverage artifact")
    parser.add_argument("--artifact-root", required=True, type=Path)
    parser.add_argument("--policy", required=True, type=Path)
    parser.add_argument("--schema", required=True, type=Path)
    parser.add_argument("--out-md", required=True, type=Path)
    parser.add_argument("--out-json", required=True, type=Path)
    args = parser.parse_args()

    run_a_path = args.artifact_root / "gh01-run-a" / "benchmark.csv"
    run_b_path = args.artifact_root / "gh01-run-b" / "benchmark.csv"
    comparison_path = args.artifact_root / "determinism.diff.json"
    gh02_summary_path = args.artifact_root / "gh02-negative" / "summary.json"
    hold_path = args.artifact_root / "gh02-negative" / "hold_register.jsonl"
    required = [run_a_path, run_b_path, comparison_path, gh02_summary_path, hold_path, args.policy, args.schema]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise SystemExit("coverage_hold: missing required evidence: " + ", ".join(missing))

    run_a = load_csv(run_a_path)
    run_b = load_csv(run_b_path)
    comparison = load_json(comparison_path)
    gh02 = load_json(gh02_summary_path)
    policy = load_json(args.policy)
    schema = load_json(args.schema)
    if len(run_a) != 1 or len(run_b) != 1:
        raise SystemExit("coverage_hold: expected exactly one row in each GH-01 benchmark")
    if not comparison.get("matches"):
        raise SystemExit("coverage_hold: deterministic comparison did not match")
    if gh02.get("fixture_count") != 10 or gh02.get("hold_count") != 10 or not gh02.get("passed"):
        raise SystemExit("coverage_hold: negative suite did not hold all expected fixtures")

    source_paths = [run_a_path, run_b_path, comparison_path, gh02_summary_path, hold_path, args.policy, args.schema]
    summary = {
        "schema_version": "qafila-evidence-coverage.v1",
        "policy_version": policy["policy_version"],
        "schema_version_event": schema["properties"]["schema_version"]["const"],
        "network_egress": policy["network_egress"],
        "external_writes": False,
        "gh01": {
            "run_a_status": run_a[0]["status"],
            "run_a_payload_hash": run_a[0]["payload_hash"],
            "run_a_benchmark": str(run_a_path),
            "run_b_status": run_b[0]["status"],
            "run_b_payload_hash": run_b[0]["payload_hash"],
            "run_b_benchmark": str(run_b_path),
            "matches": bool(comparison["matches"]),
            "comparison": str(comparison_path),
        },
        "gh02": {
            "fixture_count": gh02["fixture_count"],
            "hold_count": gh02["hold_count"],
            "hold_register": str(hold_path),
        },
        "sources": [{"path": str(path), "sha256": sha256_file(path)} for path in source_paths],
        "status": "candidate_coverage_complete",
    }
    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(render_markdown(summary), encoding="utf-8")
    args.out_json.write_text(json.dumps(summary, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": summary["status"], "gh02_hold_count": summary["gh02"]["hold_count"]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
